spring:
  application:
    name: Config-Default

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true
